### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by steelbrain** [danielmahon/atom-open-last-project#11]
This is what I get when I start my Atom
```
TypeError: Cannot read property 'destroy' of undefined
  at TabBarView.module.exports.TabBarView.removeTabForItem (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:227:28)
  at /usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:125:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:384:20)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:443:16)
  at atom-workspace.removeUntitled (/home/steel/.atom/packages/open-last-project/lib/open-last-project.js:67:37)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at PaneView.jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at PaneView.module.exports.PaneView.onItemAdded (/usr/share/atom/resources/app/src/pane-view.js:196:19)
  at /usr/share/atom/resources/app/src/pane-view.js:3:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:494:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)
```

**Comment by danielmahon** [comment]
Should be fixed with latest API updates
