### ISSUE TITLE
Warning and failed language highlighting

### ISSUE THREAD

**Issue by ricardograca** [danielmahon/atom-open-last-project#16]
There seems to be some kind of bad interaction going on with this package and `indentation-indicator` that causes the language parser to fail with the following error:

```
Failed to load grammar: /usr/share/atom/resources/app/node_modules/language-javascript/grammars/javascript.json TypeError: Cannot read property 'update' of null
  at /home/ricardo/.atom/packages/indentation-indicator/lib/indentation-indicator.coffee:32:14
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (/usr/share/atom/resources/app/src/text-editor.js:2787:27)
  at /usr/share/atom/resources/app/src/text-editor.js:196:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/usr/share/atom/resources/app/src/tokenized-buffer.js:168:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (/usr/share/atom/resources/app/src/tokenized-buffer.js:124:23)
  at /usr/share/atom/resources/app/src/tokenized-buffer.js:3:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:84:20)
  at Grammar.module.exports.Grammar.activate (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:176:48)
  at /usr/share/atom/resources/app/src/package.js:469:25
  at /usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:129:55
  at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:80:47)
  at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:168:20
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)
```

This only happens on files that were already open on the last session and are reopened on a new one. Manually opening new files after Atom has started works correctly. Disabling the `indentation-indicator` package also results in the correct behavior at all times, except that I'm left without the information provided by that package.

I already opened a [related issue](https://github.com/lee-dohm/indentation-indicator/issues/9) over there for reference.

Atom version is 0.175.0.

**Comment by ricardograca** [comment]
This issue was fixed with the latest version of `indentation-indicator`: 0.4.1
